name: Run test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cwltool
        
    - name: Set execute permission for test.py
      run: chmod +x test.py
        
    - name: Print working directory
      run: pwd

    - name: Run tests
      run: |
        cwltool test.cwl input.yml
